#!/bin/bash

scriptname=$(realpath "$0")

function editscript(){
  local script path; script="${scriptname##*/}"; path="${scriptname%/*}"; swp="$path/.$script.swp"
     if [[ ! -e "$swp" ]]; then printf "\n\n%s\n\n" "$swp"; (/usr/bin/nano "$scriptname"); exit
     else printf "\n%s is already being edited.\n%s exists; try fg or look in another window.\n" "$scriptname" "$swp"; exit;
  fi; }

function pause(){ read -p "$*" ; }

if [[ "$1" == @(edit|e|nano) ]]; then editscript; fi

. <(mpd-current.py)
printf Previos\ playlist\ lentgth:\ %s\\n "$song_length"
mpc -P seven314 add "$@"
#printf Current\ playlist\ lentgth:\ %s\\n "$song_length"
mpctitle
