#!/bin/bash

[[ -r /usr/local/bin/editscript ]] && source /usr/local/bin/editscript
[[ -r "$HOME/.config/mpd-local.conf" ]] && source "$HOME/.config/mpd-local.conf"

boldred=$(tput bold setaf 9)
tput0=$(tput sgr0)

mpccmd=( mpc -h "$mpdpass@$mpchost" )

#. <(mpd-current.py) #using mpc instead.

#[[ "$1" = . || "$1" = .\/* && "$1" != *\** ]] && set -- "$(realpath --relative-to "$musicdir" "$1")" "${@:2:}"

if (( $# == 0 )) && [[ -t 0 ]]; then
  printf '[error] No arguments and no stdin (pipe expected)\n' >&2
  printf 'Enter items to be added to currently playing or ^C to exit:\n' >&2
fi

## read from stdin:
(( $# == 0 )) && mapfile -t arr && set -- "${arr[@]}" || arr=( "$@" )

pause "$(printf %s\\n "$@")"

for i in "${!arr[@]}"; do
  [[ "${arr[i]}" = /library/music/* ]] && arr[i]="${arr[i]#/library/music/}"
done

startlength="$("${mpccmd[@]}" status %length%)"
addout="$("${mpccmd[@]}" add "$@" 2>&1)"; ec="$?"

printf \\n
printf %s\\n "${addout[@]}"
printf \\n

if (( ec )); then
  errorout="${addout##*: }"
  addfail="${addout%:*}"
  addfail="${addout#error adding }"
  addout="Error adding $boldred$*$tput0: $addout"
  mpctitle -t "$addout" -h "Error: Failed to add files..."
#  mpctitle -h "Error: Failed to add files..."
else
  printf 'Previos playlist lentgth: %s\nItem(s) added: %s\n' "$startlength" "${@:1:1}"
  [[ "${@:2:1}" ]] && printf '               %s\n' "${@:2}"
  endlength="$("${mpccmd[@]}" status %length%)"
  exec mpctitle -h "playlist: $startlength > $endlength"
fi
exit 0
