#!/bin/bash

scriptname=$(realpath "$0")

function editscript(){
  local script path; script="${scriptname##*/}"; path="${scriptname%/*}"; swp="$path/.$script.swp"
     if [[ ! -e "$swp" ]]; then printf "\n\n%s\n\n" "$swp"; (/usr/bin/nano "$scriptname"); exit
     else printf "\n%s is already being edited.\n%s exists; try fg or look in another window.\n" "$scriptname" "$swp"; exit;
  fi; }

function pause(){ read -p "$*" ; }

if [[ "$1" == @(edit|e|nano) ]]; then editscript; fi

mpccmd=( mpc -h "$mpdpass@$mpchost" )

. "$HOME/.config/local.conf"
. "$HOME/.config/mpd-local.conf"
#. <(mpd-current.py)
startlength="$("${mpccmd[@]}" status %length%)"
printf 'Previos playlist lentgth: %s\nItem(s) added: %s\n' "$startlength" "${@:1:1}"
[[ "${@:2:1}" ]] && printf '               %s\n' "${@:2}"
addout="$("${mpccmd[@]}" add "$@")"; ec="$?"
#printf Current\ playlist\ lentgth:\ %s\\n "$song_length"
if (( ec )); then
  mpctitle -t "$addout"
else
  endlength="$("${mpccmd[@]}" status %length%)"
  exec mpctitle -h "playlist: $startlength > $endlength"
fi
exit 0
