#!/bin/bash
shopt -s extglob

#read -rp "TERM=$TERM" discard

source "$XDG_CONFIG_HOME"/mpd-local.conf 2>/dev/null || . "$HOME/.config/mpd-local.conf" 2>/dev/null || /etc/default/mpd-local.conf
source mpdignore.functions

while (( $# )); do
  [[ -f "$1"   ]] && { ignored=$(realpath -m --relative-to="$musicdir" "$1"); skip=0; shift; continue; }
  [[ "$1" = -y ]] && { skip=1; shift; continue; }
  [[ "$1" = -q ]] && { quiet=1; shift; continue; }
  printf '%s is not a vaild file or argument (exit 1)\n' "$1" && exit 1
done

#mpctitleout="$(mpctitle&)"  #maybe start getting the data first in bg?

: "${ignored:=$(mpc current -f %file%)}"

(( quiet )) && printf 'Ignoring song: %s\n' "$ignored"

if [[ "$mpdhost" = @(localhost|127.0.0.1) ]]; then
  printf %s\\n "$ignored" >> "$mpdpldir"/.mpdignore.m3u
else
#  [[ "$mpdpldir" =~ \  ]] && mpdpldir="${mpdpldir// /\\ }"  #is this functional?  use awy $1=$1?
#  ignored=$(mpc current -f %file%)

## This ignorecmd=... statement seems to be far, far more than is necessary: the above only puts the file name in the .mpdignore.m3u playlist and not also load the functions and log the song so...  maybe just the printf is sufficient?
##
##  ignorecmd=$(. mpdignore.functions; logsong "ignored"; printf 'echo "%s"|tee -a %s' "$ignored" "$mpdpldir/.mpdignore.m3u")
##
##
## ssh -p"$sshport" "$mpdhost" sh -c 'printf '%s\n' "$0"|tee -a "$1"/.mpdignore.m3u' "$ignored" "$mpdpldir"

#  ignorecmd=$(printf 'echo "%s"|tee -a %s' "$ignored" "$mpdpldir/.mpdignore.m3u")
#  ssh -p"$sshport" "$mpdhost" "$ignorecmd"

#  ssh -p"$sshport" "$mpdhost" "printf '%s\n' \"$ignored\" >> \"$mpdpldir/.mpdignore.m3u\""

  printf '%s\n' "$ignored" | ssh -T -p"$sshport" "$mpdhost"   "tee -a '$mpdpldir/.mpdignore.m3u' >/dev/null"

fi

unset response
(( skip )) && read -r -p "Do you wish to skip the current song? [y/N] " response
[[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]] && exec next
