#!/bin/bash
shopt -s extglob

#read -rp "TERM=$TERM" discard

source "$XDG_CONFIG_HOME"/mpd-local.conf 2>/dev/null || . "$HOME/.config/mpd-local.conf" 2>/dev/null || /etc/default/mpd-local.conf
source mpdignore.functions

while (( "$#" )); do
  if [[ -f "$1" ]]; then
    ignored=$(realpath -m --relative-to="$musicdir" "$1")
    skip=0
    shift
  elif [[ "$1" = -y ]]; then
    skip=1; shift
  elif [[ "$1" = -q ]]; then
    quiet=true; shift
  fi
done

#mpctitleout="$(mpctitle&)"  #maybe start getting the data first in bg?

if ! "${quiet:=false}"; then printf 'Ignoring current song: %s\n' "$(mpc -f %file%)"; fi

: "${ignored:=$(mpc current -f %file%)}"

if [[ "$mpdhost" = @(localhost|127.0.0.1) ]]; then
  echo "${ignored:=$(mpc current -f %file%)}" >> "$mpdpldir"/.mpdignore.m3u
else
#  [[ "$mpdpldir" =~ \  ]] && mpdpldir="${mpdpldir// /\\ }"  #is this functional?  use awy $1=$1?
#  ignored=$(mpc current -f %file%)

## This ignorecmd=... statement seems to be far, far more than is necessary: the above only puts the file name in the .mpdignore.m3u playlist and not also load the functions and log the song so...  maybe just the printf is sufficient?
##
##  ignorecmd=$(. mpdignore.functions; logsong "ignored"; printf 'echo "%s"|tee -a %s' "$ignored" "$mpdpldir/.mpdignore.m3u")
##
##
## ssh -p"$sshport" "$mpdhost" sh -c 'printf '%s\n' "$0"|tee -a "$1"/.mpdignore.m3u' "$ignored" "$mpdpldir"

#  ignorecmd=$(printf 'echo "%s"|tee -a %s' "$ignored" "$mpdpldir/.mpdignore.m3u")
#  ssh -p"$sshport" "$mpdhost" "$ignorecmd"

#  ssh -p"$sshport" "$mpdhost" "printf '%s\n' \"$ignored\" >> \"$mpdpldir/.mpdignore.m3u\""

printf '%s\n' "$ignored" | ssh -T -p"$sshport" "$mpdhost"   "tee -a '$mpdpldir/.mpdignore.m3u' >/dev/null"

fi

unset response
(( skip )) && read -r -p "Do you wish to skip the current song? [y/N] " response
[[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]] && exec next
