#!/bin/bash
# nb: the swp file that editscript relies on is provided by nano

. /$HOME/.config/mpd-local.conf

editscript(){
  local scriptpath script path swp; scriptpath=$(realpath "$0" 2>/dev/null); script="${scriptpath##*/}"; path="${scriptpath%/*}"; swp="$path/.$script.swp"
     [[ ! -e "$swp" ]] && printf "\n\n%s\n\n" "$swp" && (/usr/bin/nano "$scriptpath") && exit
     printf "\n%s is already being edited.\n%s exists; try fg or look in another window.\n" "$scriptpath" "$swp"; exit ;}

pause(){ read -rp "$*" < /dev/tty; }

[[ "$1" == @(edit|e|-e) ]] && editscript

#this should no longer be necessary since ~/.config/mpd-local.conf has all this information and
#addresses ia the "$mpdhost" whether it uses a url or localhost.
#ssid="$(iwgetid -r)"
#
#localssids=(
# -redacted-
# -redacted-
#)
#
##printf %s\\n "${localssids[@]}"
#
#mpdlocal=false
#[[ "${localssids[@]}" == *"$ssid"* ]] && mpdlocal=true

mpc -h "$mpdpass@$mpdhostfqdn" "$@"


