#!/bin/bash
# nb: the swp file that editscript relies on is provided by nano

editscript(){
  local scriptpath script path swp; scriptpath=$(realpath "$0" 2>/dev/null); script="${scriptpath##*/}"; path="${scriptpath%/*}"; swp="$path/.$script.swp"
     [[ ! -e "$swp" ]] && printf "\n\n%s\n\n" "$swp" && (/usr/bin/nano "$scriptpath") && exit
     printf "\n%s is already being edited.\n%s exists; try fg or look in another window.\n" "$scriptpath" "$swp"; exit ;}

pause(){ read -rp "$*" < /dev/tty; }

[[ "$1" = @(edit|e|-e) ]] && editscript
[[ "$1" = @(-s|--silent) ]] && shift && list=false

if [ -t 0 ]; then
  echo "Usage: cat <file_list> | mpcpipe"
  exit 1
fi

while IFS= read -r file; do
  mpc add "$file"
  if [[ "$list" != false ]]; then
     printf %s\\n "$file"
  fi
done
