#!/bin/bash
. /usr/local/bin/editscript
. ~/.config/mpd-local.conf
#. /usr/local/bin/sourcefn
#sourcefn -l /usr/local/bin/mpdignore.functions -f sec2sex

green="$(tput setaf 2)"
tput0="$(tput sgr0)"
red="$(tput setaf 9)"


mpdc()
{ local command=$1;
  echo -ne "$command\n" | socat - UNIX-CONNECT:"$MPD_SOCK"; }
#  printf '%s\n' "$command" | socat - UNIX-CONNECT:"$MPD_SOCK"; } #doesn't work for some reason

readarray -t songstat < <( mpdc 'status\ncurrentsong' )

(( verbose==3 )) && read -rp "\$verbose=$verbose"
(( verbose==3 )) && printf %s\\n "${songstat[@]}"

unset label mbartistid

for i in "${songstat[@]}"; do
  [[ "$i" =         songid:\ * ]] && songid="${i#*: }" ##legacy ; song_id="$songid"; }
  [[ "$i" =          state:\ * ]] && { u_state="${i#*: }"; [[ "$u_state" = play ]] && state="${green}playing${tput0}" || state="${red}paused$tput0"; }
  [[ "$i" =           song:\ * ]] && { songpos="${i#*: }"; (( songpos++ )); } ##legacy song_position="$songpos"; }
  [[ "$i" = playlistlength:\ * ]] && pllength="${i#*: }" ##legacy ; song_length="$pllength"; }
#  [[ "$i" =        elapsed:\ * ]] && { elapsed="${i#*: }"; elapsed="$(sec2sex "$elapsed")"; }
#  [[ "$i" =       duration:\ * ]] && { duration="${i#*: }"; duration="$(sec2sex "$duration")"; total_time="$duration"; } ##legacy
  [[ "$i" =        elapsed:\ * ]] && { elapsed="${i#*: }"; }
  [[ "$i" =       duration:\ * ]] && duration="${i#*: }" ##legacy ; total_time="$duration"; }
  [[ "$i" =           time:\ * ]] && { percent="${i#*: }"; IFS=':' read -r elap dur <<< "$percent"; percent=$(( (100*elap)/dur )); } ##legacy percent_time="$percent"; }
  [[ "$i" =           file:\ * ]] && filepath="${i#*: }"
  [[ "$i" =          Title:\ * ]] && title="${i#*: }"
  [[ "$i" =         Artist:\ * ]] && artist="${i#*: }"
  [[ "$i" =    AlbumArtist:\ * ]] && albumartist="${i#*: }" ##legacy ; album_artist="$albumartist"; }
  [[ "$i" =          Album:\ * ]] && album="${i#*: }"
  [[ "$i" =           Year:\ * ]] && year="${i#*: }"  ##issue
  [[ "$i" =         volume:\ * ]] && volume="${i#*: }"
  [[ "$i" =         repeat:\ * ]] && { u_repeat="${i#*: }"; (( u_repeat )) && repeat="$green⟳$tput0" || repeat='⟳'; }
  [[ "$i" =         single:\ * ]] && { u_single="${i#*: }"; (( u_single )) && single='✅' || unset single; }
  [[ "$i" =         random:\ * ]] && { u_random="${i#*: }"; (( u_random )) && random='✅' || random='❌'; }
  [[ "$i" =        consume:\ * ]] && { u_consume="${i#*: }"; (( u_consume )) && consume='✅' || consume='❌'; }
  [[ "$i" =           Disc:\ * ]] && disc="${i#*: }"
  [[ "$i" =          Genre:\ * ]] && genre="${i#*: }"
  [[ "$i" =          Track:\ * ]] && track="${i#*: }"
  [[ "$i" =        Comment:\ * ]] && comment="${i#*: }" ##issue
  [[ "$i" =      Performer:\ * ]] && performer="${i#*: }" ## issue
  [[ "$i" =           Date:\ * ]] && { date="${i#*: }"; date="${i%%-*}"; }  ## issue
  [[ "$i" =     nextsongid:\ * ]] && nextid="${i#*: }"
# [[ "$i" =      partition:\ * ]] && partition="${i#*: }"
# [[ "$i" =       playlist:\ * ]] && playlistid="${i#*: }"
# [[ "$i" =      mixrampdb:\ * ]] && mixrampdb="${i#*: }"
# [[ "$i" =   mixrampdelay:\ * ]] && mixrampdelay="${i#*: }"
# [[ "$i" =        bitrate:\ * ]] && bitrate="${i#*: }"
# [[ "$i" =       nextsong:\ * ]] && nextsong="${i#*: }"
# [[ "$i" =         Format:\ * ]] && format="${i#*: }"
# [[ "$i" =    AlbumArtist:\ * ]] && albumartist="${i#*: }"
# [[ "$i" =     ArtistSort:\ * ]] && artistsort="${i#*: }"
# [[ "$i" =   OriginalDate:\ * ]] && originaldate="${i#*: }"
# [[ "$i" =  Last-Modified:\ * ]] && lastmodified="${i#*: }"
# [[ "$i" =          Label:\ * ]] && label+=( "${i#*: }" ) ##issue
# [[ "$i" =           Time:\ * ]] && Time="${i#*: }"   ##issue
# [[ "$i" =            AlbumArtistSort:\ * ]] && albumartsort="${i#: }"
# [[ "$i" =  MUSICBRAINZ_ALBUMARTISTID:\ * ]] && mbalbumartid="${i#*: }"
  [[ "$i" =       MUSICBRAINZ_ARTISTID:\ * ]] && mbartistid+=( "${i#*: }" )
  [[ "$i" =        MUSICBRAINZ_ALBUMID:\ * ]] && mbalbumid="${i#*: }"
  [[ "$i" = MUSICBRAINZ_RELEASETRACKID:\ * ]] && mbreltrackid="${i#*: }"
done

(( verbose==3 )) && read -rp "\$nextid: $nextid"

readarray -t nextsong < <(mpdc "playlistid ${nextid}" )

(( verbose==3 )) && printf %s\\n "${nextsong[@]}"

unset next_label next_mbartistid

for i in "${nextsong[@]}"; do
##  [[ "$i" =           song:\ * ]] && songpos="${i#*: }" && (( songpos++ )) && song_position="$songpos" ##legacy
#  [[ "$i" =       duration:\ * ]] && { next_duration="${i#*: }"; next_duration="$(sec2sex "$next_duration")"; } ##issue
  [[ "$i" =       duration:\ * ]] && { next_duration="${i#*: }"; } ##issue
  [[ "$i" =           file:\ * ]] && next_filepath="${i#*: }"
  [[ "$i" =          Title:\ * ]] && next_title="${i#*: }"
  [[ "$i" =         Artist:\ * ]] && next_artist="${i#*: }"
  [[ "$i" =    AlbumArtist:\ * ]] && next_albumartist="${i#*: }" ##legacy ; next_album_artist="$next_albumartist"; }
  [[ "$i" =          Album:\ * ]] && next_album="${i#*: }"
# [[ "$i" =           Year:\ * ]] && year="${i#*: }"  ##issue
  [[ "$i" =           Disc:\ * ]] && next_disc="${i#*: }"
  [[ "$i" =          Genre:\ * ]] && next_genre="${i#*: }"
  [[ "$i" =          Track:\ * ]] && next_track="${i#*: }"
  [[ "$i" =        Comment:\ * ]] && next_comment="${i#*: }" ##issue
  [[ "$i" =      Performer:\ * ]] && next_performer="${i#*: }" ## issue
  [[ "$i" =           Date:\ * ]] && { next_date="${i#*: }"; next_date="${i%%-*}"; }  ## issue
  [[ "$i" =     nextsongid:\ * ]] && nextid="${i#*: }"
# [[ "$i" =         Format:\ * ]] && next_format="${i#*: }"
# [[ "$i" =    AlbumArtist:\ * ]] && next_albumartist="${i#*: }"
# [[ "$i" =     ArtistSort:\ * ]] && next_artistsort="${i#*: }"
# [[ "$i" =   OriginalDate:\ * ]] && next_originaldate="${i#*: }"
# [[ "$i" =  Last-Modified:\ * ]] && next_lastmodified="${i#*: }"
# [[ "$i" =          Label:\ * ]] && next_label+=( "${i#*: }" ) ##issue
  [[ "$i" =           Time:\ * ]] && next_time="${i#*: }"   ##issue
# [[ "$i" =            AlbumArtistSort:\ * ]] && next_albumartsort="${i#: }"
# [[ "$i" =  MUSICBRAINZ_ALBUMARTISTID:\ * ]] && next_mbalbumartid="${i#*: }"
  [[ "$i" =       MUSICBRAINZ_ARTISTID:\ * ]] && next_mbartistid+=( "${i#*: }" )
  [[ "$i" =        MUSICBRAINZ_ALBUMID:\ * ]] && next_mbalbumid="${i#*: }"
  [[ "$i" = MUSICBRAINZ_RELEASETRACKID:\ * ]] && next_mbreltrackid="${i#*: }"
done

if [[ "$1" = @(--print|-p) ]]; then
  printf "songid='%s'\n" "$songid"
  printf "state='%s'\n" "$state"
  printf "song_position='%s'\n" "$song_position"
  printf "pllength='%s'\n" "$pllength"
  printf "song_length='%s'\n" "$song_length"
  printf "u_state='%s'\n" "$u_state"
  printf "volume='%s'\n" "$volume"
  printf "pllength='%s'\n" "$pllength"
  printf "repeat='%s'\n" "$repeat"
  printf "u_repeat='%s'\n" "$u_repeat"
  printf "percent='%s%%'\n" "$percent"
  printf 'percent_time=%s\n' "$percent_time"
  printf "elapsed='%s'\n" "$elapsed"
  printf "duration='%s'\n" "$duration"
  printf "total_time='%s'\n" "$total_time"
  printf 'filepath=%s\n' "${filepath@Q}"
  printf 'title=%s\n' "${title@Q}"
  printf 'artist=%s\n' "${artist@Q}"
  printf "albumartist='%s'\n" "$albumartist"
  printf 'album=%s\n' "${album@Q}"
  printf "year='%s'\n" "$year"
  printf "single='%s'\n" "$single"
  printf "u_random='%s'\n" "$u_random"
  printf "random='%s'\n" "$random"
  printf "u_consume='%s'\n" "$u_consume"
  printf "consume='%s'\n" "$consume"
  printf "disc='%s'\n" "$disc"
  printf "genre='%s'\n" "$genre"
  printf "track='%s'\n" "$track"
  printf "comment='%s'\n" "$comment"
  printf "performer='%s'\n" "$performer"
  printf "date='%s'\n" "$date"
  printf "mbartistid='%s'\n" "${mbartistid[@]}"
  printf "mbalbumid='%s'\n" "$mbalbumid"
  printf "mbreltrackid='%s'\n" "$mbreltrackid"

  printf '\n# Next song variables\n'
  printf "next_duration='%s'\n" "$next_duration"
  printf 'next_filepath=%s\n' "${next_filepath@Q}"
  printf 'next_title=%s\n' "${next_title@Q}"
  printf 'next_artist=%s\n' "${next_artist@Q}"
  printf 'next_albumartist=%s\n' "${next_albumartist@Q}"
  printf 'next_album=%s\n' "${next_album@Q}"
  printf "next_disc='%s'\n" "$next_disc"
  printf "next_genre='%s'\n" "$next_genre"
  printf "next_track='%s'\n" "$next_track"
  printf "next_comment='%s'\n" "$next_comment"
  printf "next_performer='%s'\n" "$next_performer"
  printf "next_date='%s'\n" "$next_date"
  printf "next_time='%s'\n" "$next_time"
  printf "next_mbartistid='%s'\n" "${next_mbartistid[@]}"
  printf "next_mbalbumid='%s'\n" "$next_mbalbumid"
  printf "next_mbreltrackid='%s'\n" "$next_mbreltrackid"
fi
