#!/bin/bash
musicdir=/library/music
scriptname=$(realpath "$0" 2>/dev/null)

editscript(){
  local script path; script="${scriptname##*/}"; path="${scriptname%/*}"; swp="$path/.$script.swp"
     if [[ ! -e "$swp" ]]; then printf "\n\n%s\n\n" "$swp"; (/usr/bin/nano "$scriptname"); exit
     else printf "\n%s is already being edited.\n%s exists; try fg or look in another window.\n" "$scriptname" "$swp"; exit;
  fi; }

pause(){ read -p "$*" ; }

title(){
artist="$(mpc current -f %artist%)"
album="$(mpc current -f %album%)"
title="$(mpc current -f %title%)"
printf "\n\033[0mArtist: %s\nAlbum : %s\nTitle : %s\n" "$artist" "$album" "$title"

mpc current -f "%file%"|awk -F / -v OFS=/ '{$1="\033[1;33m" $1 "\033[0m"; $NF="\033[1;34m" $NF "\033[0m"; print}'

#mpc current -f "%title% on %album% by %artist%\n%file%"
printf '\n'
mpc queued -f "%file%"|awk -F / -v OFS=/ '{$1="Up next: \033[1;33m" $1 "\033[0m"; $NF="\033[1;34m" $NF "\033[0m"; print}'
printf '\n'
}

if [[ "$1" == @(edit|e|nano) ]]; then editscript; fi

clear -x

title

while read -r line
  do
    i="${line/ : player: /\/ }"
    i=$(printf '%s' "$i"|awk -F / -v OFS=/ '{$1="\033[1;32m" $1 "\033[0m"; $2 = "\033[1;33m" $2 "\033[0m"; $NF = "\033[1;34m" $NF "\033[0m"; print}')
    i="${i/\//:}"
#    printf '%s\n' "$i"
    playedarr["$n"]="$i"
    ((n++))
  done < <(\grep player /var/log/mpd/mpd.log|tail -n 120)

for ((n-1; n>=0; n--)); do
  revarray+=( "$( printf '%s ' ${playedarr[$n]} )" )
done



#j=$(gum choose --height 40 "${playedarr[@]}") || exit

result=$(gum choose --height 40  "${revarray[@]:1}") ||		# Remove everything up to the first double quote
		 exit 												# or exit
[[ ! "$result" ]] && echo "Result empty; exit 1" && exit 1  # check again?
resultpath="${result#*\"}"
resultpath="${resultpath%\"*}" 									# Remove everything after the last double quote
resultdir="${resultpath%\/*}"

#if [[ $string =~ \"(.*)\" ]]; then
#    j="${BASH_REMATCH[1]}"									# this matches the capture group in the last [[ =~
#fi															# not especially useful here.

exitapp=$(gum choose "mediainfo" "picard" "ls ${d}")
clear -x
pause "$resultpath"

 if [[ "$exitapp" == mediainfo ]]
   then
    readarray -t miarray < <(mediainfo "/library/music/$resultpath")

    printf %s\\n "${miarray[@]}"

    michoice="$(gum choose "${miarray[@]}" --header.bold --cursor.italic --height=$((lines-5))  --header.padding="0 2")"
    [[ "$michoice" = MusicBrainz\ Release\ Track\ Id* ]] && printf '\n\nControl-Cick URL to open in browser: https://musicbrainz.org/track/%s\n\nAt some point there will be a confirm here to open in Chrome!\n' "${michoice#* : }"
   elif
     [[ "$exitapp" == picard ]]; then picard "$musicdir/$resultdir"
   elif
     [[ "$exitapp" == "ls $d" ]]; then echo "$resultdir:"; ls "/library/music/$d"
 fi
