#!/bin/bash

scriptname=$(realpath "$0")

function editscript(){
  local script path; script="${scriptname##*/}"; path="${scriptname%/*}"; swp="$path/.$script.swp"
  if [[ ! -e "$swp" ]]; then 
    printf "\n\n%s\n\n" "$swp"; 
    (/usr/bin/nano "$scriptname"); exit
  else 
    printf "\n%s is already being edited.\n%s exists; try fg or look in another window.\n" "$scriptname" "$swp"; exit
  fi
}

function pause(){ read -p "$*" ; }

if [[ "$1" == "edit" ]] || [[ "$1" == "e" ]] || [[ "$1" == "nano" ]]; then
  editscript "$1"
elif [[ "$1" == "help" ]] || [[ "$1" == "-h" ]]; then
  printf "Call `%s (e|edit|nano)` to edit the script.\n" "$0"
  exit 0
fi

ip="127.0.0.1"
sink=""

while [[ "$#" -gt 0 ]]; do
  case $1 in
    --compaq) ip="192.168.12.22"; shift ;;
    --gig|--gigabyte) ip="192.168.1.2"; shift ;;
    --mute|mute) cmd="--toggle-mute"; shift ;;
    --sink) sink="$2"; shift 2 ;;
    *)
#      if [[ "$1" =~ ^-?[0-9]+$ ]]; then
#      if [[ "$1" =~ ^(-|\+)?[0-9]{1,3}$ ]]; then
#        if (( "$1" >= 0 )); then
#          cmd="--set-volume $1"
#        else
#          cmd="--change-volume $1"
#        fi
      if [[ "$1" =~ ^(-|\+)?[0-9]{1,3}$ ]]; then
        if [[ "$1" =~ ^[0-9]+$ ]]; then
          cmd="--set-volume $1"  # Unsigned sets volume
        else
          cmd="--change-volume $1"  # Signed changes volume
        fi
      else
        echo "Unknown parameter passed: $1"
        exit 1
      fi
      shift
      ;;
  esac
done

if [[ -z "$sink" ]]; then
  sink="$(pulsemixer --server="$ip" --list-sinks | grep JBL | awk '{print $3}')"
  sink="${sink%,}"
  pause "$sink"
fi

if [[ -n "$cmd" ]]; then
  pulsemixer --server="$ip" --id "$sink" $cmd
else
  echo "Usage: $0 --compaq|--gig|--mute|<volume_change>"
  exit 1
fi
